export const TASK_ACTION_TYPES = {
    SET_TASK_ARRAY: 'SET_TASK_ARRAY',
    SET_IS_TOGGLE_CALENDAR: 'SET_IS_TOGGLE_CALENDAR',
    SET_DATE: 'SET_DATE',
    SET_SEARCH_FIELD: 'SET_SEARCH_FIELD',
    SET_TASK_FILL: 'SET_TASK_FILL',
}